---
- name: Run common tasks on all hosts
  hosts: all
  remote_user: root
  # remote_user: user
  # become: yes
  # become_method: sudo
  roles: common

- name: Run search roles on only workstations
  hosts: workstations
  remote_user: root
  roles: search

- name: Run destroy roles on only servers
  hosts: servers
  remote_user: root
  roles: search
